version: '3'

networks:
  laravel-settings:

services:
  mysql:
    image: mysql:5.7
    container_name: ls-mysql
    tmpfs: /var/lib/mysql
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: laravel
      MYSQL_USER: root
    networks:
      - laravel-settings

  php:
    image: thomasowow/laravel-php:8.0
    container_name: ls-php
    tty: true
    volumes:
      - .:/var/www/html:cached
    networks:
      - laravel-settings
